name: One Identity Frontend CI Build
description: CI workflow to build, package and test One Identity frontend applications  

on:
  push:
    branches: [ v100 ]
  pull_request:
    branches: [ v100, v93 ]

jobs:
  ci:
    name: Build, package, and test applications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup  # Setup steps

      # Need to use nx cloud/ nx replay instead
      # - name: Cache Nx
      #   uses: actions/cache@v5
      #   with:
      #     path: ./imxweb/.nx/cache
      #     key: nx-${{ runner.os }}-${{ hashFiles('imxweb/package-lock.json') }}
      #     restore-keys: |
      #       nx-${{ runner.os }}-
      
      - name: Build All
        working-directory: ./imxweb
        run: npx nx run-many -t build -c production
      
      - name: Zip applications          
        run: |
          # Dynamically get app names from projects dir
          apps=$(ls -d ./imxweb/projects/*-app* 2>/dev/null | xargs -n1 basename)
          for app in $apps; do
            if [ -d "./imxweb/dist/$app" ]; then
              ( cd "./imxweb/dist/$app" && zip -r "../Html_${app}.zip" . )
            fi
          done
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: imxweb-apps
          path: ./imxweb/dist/Html_*.zip

      # Tests currently do not work
      # - name: Test All
      #   working-directory: ./imxweb
      #   run: npm run nx:test-ci
      #   timeout-minutes: 30
      